{{- $context := . }}
{{- range .Values.mastodon.sidekiq.workers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mastodon.fullname" $context }}-sidekiq-{{ .name }}
  labels:
    {{- include "mastodon.labels" $context | nindent 4 }}
    app.kubernetes.io/component: sidekiq-{{ .name }}
    app.kubernetes.io/part-of: rails
  annotations:
    {{- with $context.Values.deploymentAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if (has "scheduler" .queues) }}
    {{- if (gt (int .replicas) 1) }}
      {{ fail "The scheduler queue should never have more than 1 replicas" }}
    {{- end }}
  strategy:
    type: Recreate
  {{- end }}
  revisionHistoryLimit: {{ $context.Values.mastodon.revisionHistoryLimit }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels" $context | nindent 6 }}
      app.kubernetes.io/component: sidekiq-{{ .name }}
      app.kubernetes.io/part-of: rails
  template:
    metadata:
      annotations:
        {{- with $context.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        # roll the pods to pick up any db migrations or other changes
        {{- include "mastodon.rollingPodAnnotations" $context | nindent 8 }}
        checksum/config-secrets-smtp: {{ include ( print $.Template.BasePath "/secret-smtp.yaml" ) $context | sha256sum | quote }}
      labels:
        {{- include "mastodon.selectorLabels" $context | nindent 8 }}
        app.kubernetes.io/component: sidekiq-{{ .name }}
        app.kubernetes.io/part-of: rails
    spec:
      {{- with $context.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mastodon.serviceAccountName" $context }}
      {{- with (default $context.Values.podSecurityContext $context.Values.mastodon.sidekiq.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default (default $context.Values.affinity $context.Values.mastodon.sidekiq.affinity) .affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $context.Values.mastodon.extraVolumes (not $context.Values.mastodon.s3.enabled) }}
      volumes:
        {{- if not $context.Values.mastodon.s3.enabled }}
        - name: assets
          persistentVolumeClaim:
            claimName: {{ template "mastodon.pvc.assets" $context }}
        - name: system
          persistentVolumeClaim:
            claimName: {{ template "mastodon.pvc.system" $context }}
        {{- end }}
        {{- if gt (len $context.Values.mastodon.extraVolumes) 0 }}
        {{ toYaml $context.Values.mastodon.extraVolumes | nindent 8}}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ $context.Chart.Name }}
          securityContext:
            {{- toYaml $context.Values.mastodon.sidekiq.securityContext | nindent 12 }}
          image: "{{ $context.Values.image.repository }}:{{ $context.Values.image.tag | default $context.Chart.AppVersion }}"
          imagePullPolicy: {{ $context.Values.image.pullPolicy }}
          command:
            - bundle
            - exec
            - sidekiq
            - -c
            - {{ .concurrency | quote }}
            {{- range .queues }}
            - -q
            - {{ . | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "mastodon.fullname" $context }}-env
            - secretRef:
                name: {{ template "mastodon.secretName" $context }}
            {{- with $context.Values.mastodon.extraEnvFrom }}
            - configMapRef:
                name: {{ . }}
            {{- end}}
          env:
            - name: "DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: {{ template "mastodon.postgresql.secretName" $context }}
                  key: password
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ template "mastodon.redis.secretName" $context }}
                  key: {{ $context.Values.redis.auth.existingSecretPasswordKey }}
            {{- if and $context.Values.redis.sidekiq.enabled $context.Values.redis.sidekiq.auth.existingSecret }}
            - name: "SIDEKIQ_REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ template "mastodon.redis.sidekiq.secretName" . }}
                  key: {{ $context.Values.redis.auth.existingSecretPasswordKey }}
            {{- end }}
            {{- if and $context.Values.redis.cache.enabled $context.Values.redis.cache.auth.existingSecret }}
            - name: "CACHE_REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ template "mastodon.redis.cache.secretName" . }}
                  key: {{ $context.Values.redis.auth.existingSecretPasswordKey }}
            {{- end }}
            - name: "SMTP_SERVER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "mastodon.smtp.secretName" $context }}
                  key: server
                  optional: true
            - name: "SMTP_LOGIN"
              valueFrom:
                secretKeyRef:
                  name: {{ include "mastodon.smtp.secretName" $context }}
                  key: login
                  optional: true
            - name: "SMTP_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "mastodon.smtp.secretName" $context }}
                  key: password
            {{- if (and $context.Values.mastodon.s3.enabled $context.Values.mastodon.s3.existingSecret) }}
            {{- if $context.Values.mastodon.s3.secretKeys.s3Hostname }}
            - name: "S3_HOSTNAME"
              valueFrom:
                secretKeyRef:
                  name: {{ $context.Values.mastodon.s3.existingSecret }}
                  key: {{ $context.Values.mastodon.s3.secretKeys.s3Hostname }}
            {{- end }}
            - name: "S3_ENDPOINT"
              valueFrom:
                secretKeyRef:
                  name: {{ $context.Values.mastodon.s3.existingSecret }}
                  key: {{ $context.Values.mastodon.s3.secretKeys.s3Endpoint }}
            {{- if $context.Values.mastodon.s3.secretKeys.s3Region }}
            - name: "S3_REGION"
              valueFrom:
                secretKeyRef:
                  name: {{ $context.Values.mastodon.s3.existingSecret }}
                  key: {{ $context.Values.mastodon.s3.secretKeys.s3Region }}
            {{- end }}
            - name: "S3_BUCKET"
              valueFrom:
                secretKeyRef:
                  name: {{ $context.Values.mastodon.s3.existingSecret }}
                  key: {{ $context.Values.mastodon.s3.secretKeys.s3Bucket }}
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: {{ $context.Values.mastodon.s3.existingSecret }}
                  key: {{ $context.Values.mastodon.s3.secretKeys.s3AccessKeyID }}
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ $context.Values.mastodon.s3.existingSecret }}
                  key: {{ $context.Values.mastodon.s3.secretKeys.s3AccessKey }}
            {{- end }}
            {{- if and $context.Values.mastodon.deepl.enabled }}
            - name: "DEEPL_API_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ $context.Values.mastodon.deepl.apiKeySecretRef.name }}
                  key: {{ $context.Values.mastodon.deepl.apiKeySecretRef.key }}
            {{- end }}
            {{- if or $context.Values.mastodon.sidekiq.otel.enabled (and $context.Values.mastodon.otel.enabled (ne $context.Values.mastodon.sidekiq.otel.enabled false)) }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ coalesce $context.Values.mastodon.sidekiq.otel.endpointUri $context.Values.mastodon.otel.endpointUri }}
            - name: OTEL_SERVICE_NAME_PREFIX
              value: {{ coalesce $context.Values.mastodon.sidekiq.otel.namePrefix $context.Values.mastodon.otel.namePrefix }}
            - name: OTEL_SERVICE_NAME_SEPARATOR
              value: "{{ coalesce $context.Values.mastodon.sidekiq.otel.nameSeparator $context.Values.mastodon.otel.nameSeparator }}"
            {{- end }}
            {{- with $context.Values.mastodon.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if or $context.Values.mastodon.extraVolumeMounts (not $context.Values.mastodon.s3.enabled)}}
          volumeMounts:
          {{- if not $context.Values.mastodon.s3.enabled }}
            - name: assets
              mountPath: /opt/mastodon/public/assets
            - name: system
              mountPath: /opt/mastodon/public/system
          {{- end }}
          {{- if gt (len $context.Values.mastodon.extraVolumeMounts) 0 }}
          {{- toYaml $context.Values.mastodon.extraVolumeMounts | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml (default (default $context.Values.resources $context.Values.mastodon.sidekiq.resources) .resources) | nindent 12 }}
      {{- with $context.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $context.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
